### ISSUE TITLE
请教如何使用serialport

### ISSUE THREAD

**Issue by hormers** [Bread-etc/electron-vite-serialport#1]
如题，我想知道作者是如何引入serialport而不报错的，我使用 require 引入会报错

**Comment by Bread-etc** [comment]
你好，首先要更改`main/index.ts`下的`webPreferneces`项，加入`nodeIntegration: true`和`contextIsolation: false`这两项用于集成node、关闭上下文隔离；然后安装`node-gyp`和`electron-rebuild`；然后再打开到node_modules\.bin\，运行对应目录下的electron-rebuild.cmd重新执行编译，就可以使用 require 引入了！😎
祝你开发愉快🎉

**Comment by hormers** [comment]
感谢！
